services:
  rf_agent:
    build: .
    image: rf_image:latest
    runtime: nvidia
    network_mode: host
    privileged: true
    entrypoint: bash /home/run_agent.sh
    hostname: jetson
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_NAMESPACE=${ROS_NAMESPACE:-jetson}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - ./run_agent.sh:/home/run_agent.sh
      - ../src:/home/rf_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
